name: dsc_iraq_platform
description: A dashboard for platform of developer student clubs in iraq. 

publish_to: 'iqds.club'

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ">=6.1.3 <7.0.0"
  flutter_bloc: ">=6.1.3 < 7.0.0"
  url_launcher: ">=6.0.2 <7.0.0"
  flutter_svg: ">=0.19.3 <1.0.0"
  web_socket_channel: ">=2.0.0 <3.0.0"
  equatable: ">=2.0.0 <3.0.0"
  dartz: ">=0.9.2 <1.0.0"
  moor: ">=4.1.0 <5.0.0"
  extended_image: ">=3.0.0 <4.0.0"
  dio: ">=2.2.2 <4.0.0"
  get_it: ">=6.0.0 <7.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  mockito: ^4.1.2
  built_collection: ^5.0.0
  built_value: ^8.0.2
  moor_generator: ^4.1.0

flutter:

  uses-material-design: true

  assets:
    - images/
    - languages/

  fonts:
    - family: Tajawal
      fonts:
        - asset: fonts/Tajawal/ExtraLight.ttf
          weight: 200
        - asset: fonts/Tajawal/Light.ttf
          weight: 300
        - asset: fonts/Tajawal/Regular.ttf
          weight: 400
        - asset: fonts/Tajawal/Medium.ttf
          weight: 500
        - asset: fonts/Tajawal/Bold.ttf
          weight: 700
        - asset: fonts/Tajawal/ExtraBold.ttf
          weight: 800
        - asset: fonts/Tajawal/Black.ttf
          weight: 900
